version: "3.7"
services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - backend
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    ports:
      - "5432:5432"
    networks:
      - backend
networks:
  backend:
    driver: "bridge"
